/** Languages to translate into: `en` goes to the model, `native` to the menu. */
export const LANGUAGES: { en: string; native: string }[] = [
  { en: "English", native: "English" },
  { en: "Indonesian", native: "Bahasa Indonesia" },
  { en: "Malay", native: "Bahasa Melayu" },
  { en: "Javanese", native: "Basa Jawa" },
  { en: "Sundanese", native: "Basa Sunda" },
  { en: "Simplified Chinese", native: "中文（简体）" },
  { en: "Traditional Chinese", native: "中文（繁體）" },
  { en: "Japanese", native: "日本語" },
  { en: "Korean", native: "한국어" },
  { en: "Thai", native: "ไทย" },
  { en: "Vietnamese", native: "Tiếng Việt" },
  { en: "Filipino", native: "Filipino" },
  { en: "Hindi", native: "हिन्दी" },
  { en: "Arabic", native: "العربية" },
  { en: "Turkish", native: "Türkçe" },
  { en: "Russian", native: "Русский" },
  { en: "Spanish", native: "Español" },
  { en: "Portuguese", native: "Português" },
  { en: "French", native: "Français" },
  { en: "German", native: "Deutsch" },
  { en: "Italian", native: "Italiano" },
  { en: "Dutch", native: "Nederlands" },
];
